sudo: required
services:
    - docker

before_install:
    - docker build -t mtd643/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mtd643/docker-react npm run test

#dockerreact-env.eba-dbnbcecf.us-east-2.elasticbeanstalk.com/
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-600340103635"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY